name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 4.0.0)"
        required: true
        type: string
      tag:
        description: "Git tag (e.g., v4.0.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Update version in package.json
        run: |
          $packageJson = Get-Content package.json | ConvertFrom-Json
          $packageJson.version = "${{ inputs.version }}"
          $packageJson | ConvertTo-Json -Depth 100 | Set-Content package.json
        shell: pwsh

      - name: Build Windows binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run build:win

      - name: Create git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          try {
            git commit -m "chore: bump version to ${{ inputs.version }}"
          } catch {
            Write-Host "No changes to commit"
          }
          git tag "${{ inputs.tag }}" -f
          git push origin main --tags -f
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: "VLC Discord RP ${{ inputs.tag }}"
          body: |
            ## 🚀 VLC Discord RP ${{ inputs.tag }}

            ### Installation Options
            - **Setup Installer** (`vlc-rpc-${{ inputs.version }}-setup.exe`): Traditional Windows installer with auto-updates
            - **Portable Version** (`vlc-rpc-${{ inputs.version }}-portable.exe`): No installation required, run anywhere

            ### Changes
            See [CHANGELOG.md](https://github.com/valentin-marquez/vlc-rpc/blob/main/CHANGELOG.md) for detailed changes.
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.yml
            dist/*.blockmap
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
